export const columns = [
   {name: 'BLD SERIAL NUMBER', uid: 'bloodSerialNum'},
   {name: 'BLOOD TYPE', uid: 'bloodType'},
   {name: 'BLOOD COMPONENT', uid: 'bloodComponent'},
   {name: 'EXPIRATION DATE', uid: 'expDate'},
   {name: 'STATUS', uid: 'status'},
   {name: 'ACTIONS', uid: 'actions'},
];
export const bloods = [
   {
      id: 1,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'B+',
      bloodComponent: 'WHOLE BLOOD',
      expDate: '9/20/2021',
      status: 'Available',
   },
   {
      id: 2,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'O+',
      bloodComponent: 'FRESH FROZEN PLASMA',
      expDate: '9/20/2021',
      status: 'Reserved',
   },
   {
      id: 3,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'AB+',
      bloodComponent: 'PACKED RED BLOOD CELLS',
      expDate: '9/20/2021',
      status: 'Reserved',
   },
   {
      id: 4,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'B-',
      bloodComponent: 'WHOLE BLOOD',
      expDate: '9/20/2021',
      status: 'Reserved',
   },
   {
      id: 5,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'AB+',
      bloodComponent: 'WHOLE BLOOD',
      expDate: '9/20/2021',
      status: 'Available',
   },
   {
      id: 6,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'A+',
      bloodComponent: 'WHOLE BLOOD',
      expDate: '9/20/2021',
      status: 'Available',
   },
   {
      id: 7,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'O+',
      bloodComponent: 'PACKED RED BLOOD CELLS',
      expDate: '9/20/2021',
      status: 'Available',
   },
   {
      id: 8,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'B+',
      bloodComponent: 'FRESH FROZEN PLASMA',
      expDate: '9/20/2021',
      status: 'Available',
   },
   {
      id: 9,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'AB+',
      bloodComponent: 'WHOLE BLOOD',
      expDate: '9/20/2021',
      status: 'Available',
   },
   {
      id: 10,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'B+',
      bloodComponent: 'PACKED RED BLOOD CELLS',
      expDate: '9/20/2021',
      status: 'Available',
   },
   {
      id: 11,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'O-',
      bloodComponent: 'WHOLE BLOOD',
      expDate: '9/20/2021',
      status: 'Reserved',
   },
   {
      id: 12,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'B+',
      bloodComponent: 'WHOLE BLOOD',
      expDate: '9/20/2021',
      status: 'Available',
   },
   {
      id: 13,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'AB+',
      bloodComponent: 'WHOLE BLOOD',
      expDate: '9/20/2021',
      status: 'Available',
   },
   {
      id: 14,
      bloodSerialNum: 'W1234 06 123456',
      bloodType: 'A+',
      bloodComponent: 'FRESH FROZEN PLASMA',
      expDate: '9/20/2021',
      status: 'Reserved',
   },
   
];
